#!/usr/bin/env bash
# Install Nginx Web Server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow "Nginx HTTP"
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
