#!/usr/bin/env bash
# Configure nginx and add header

sudo apt-get upgrade
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx start
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
sudo sed -i "/server_name _;/a \ \n \ \ \ \ add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
