#!/usr/bin/env bash
# Print Domain details

if [ "$2" = "www" ];then
    dig "www.$1" | grep "www.$1" | awk 'NR==3{print "The subdomain www is a " $4 " record and points to " $5; exit}'
elif [ "$2" = "lb-01" ];then
    dig "lb-01.$1" | grep "lb-01.$1" | awk 'NR==3{print "The subdomain lb-01 is a " $4 " record and points to " $5; exit}'
elif [ "$2" = "web-01" ];then
    dig "web-01.$1" | grep "web-01.$1" | awk 'NR==3{print "The subdomain web-01 is a " $4 " record and points to " $5; exit}'
elif [ "$2" = "web-02" ];then
    dig "web-02.$1" | grep "web-02.$1" | awk 'NR==3{print "The subdomain web-02 is a " $4 " record and points to " $5; exit}'
else
    dig "www.$1" | grep "www.$1" | awk 'NR==3{print "The subdomain www is a " $4 " record and points to " $5; exit}'
    dig "lb-01.$1" | grep "lb-01.$1" | awk 'NR==3{print "The subdomain lb-01 is a " $4 " record and points to " $5; exit}'
    dig "web-01.$1" | grep "web-01.$1" | awk 'NR==3{print "The subdomain web-01 is a " $4 " record and points to " $5; exit}'
    dig "web-02.$1" | grep "web-02.$1" | awk 'NR==3{print "The subdomain web-02 is a " $4 " record and points to " $5; exit}'
fi