#!/bin/env bash
# Configure HAProxy
sudo apt update
sudo apt upgrade -y

sudo apt-get install -y apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9

sudo apt-get install -y haproxy=2.9.\*

echo "backend webback" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tbalance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tmode http" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tserver server1 100.25.154.230:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tserver server2 54.146.64.131:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "frontend webfront" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tbind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tmode http" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\tdefault_backend webback" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart