#!/usr/bin/env bash
# Run a command with a different user

if [ "$#" -lt 1 ]; then
	whoami
	exit
fi

HOME="/"
NAME="${1//$HOME/}"
IS_USER=$(grep -c "$NAME" /etc/passwd)

if [ "$IS_USER" ]; then
	su -c whoami "$NAME"
	echo "$NAME"
else
	exit
fi
